# Generated by Django 2.0.1 on 2018-05-03 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_users_to_existing_an_fields(apps, schema_editor):
    Ausgabe = apps.get_model('main_app', 'Ausgabe')
    User = apps.get_model('auth', 'User')
    for a in Ausgabe.objects.all():
        for u in User.objects.all().exclude(is_superuser=True):
            a.an.add(u)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausgleichszahlung',
            name='an',
        ),
        migrations.RemoveField(
            model_name='ausgleichszahlung',
            name='von',
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='an',
            field=models.ManyToManyField(limit_choices_to={'is_superuser': False}, related_name='an_mitbewohnis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='mitbewohni',
            field=models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='von_mitbewohni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ausgleichszahlung',
        ),
        migrations.RunPython(
            add_users_to_existing_an_fields, reverse_code=migrations.RunPython.noop
            ),

    ]
